/*
 * MinIO .NET Library for Amazon S3 Compatible Cloud Storage, (C) 2020 MinIO, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace Minio.DataModel
{
    /// <summary>
    /// Stores raw json events generated by ListenBucketNotifications
    /// The Minio client doesn't depend on a JSON library so we can let
    ///  the caller use a library of their choice
    /// </summary>
    public class MinioNotificationRaw
    {
        public string json;

        public MinioNotificationRaw(string json)
        {
            this.json = json;
        }
    }

    /// <summary>
    /// Helper class to deserialize notifications generated
    /// from MinioNotificaitonRaw by ListenBucketNotifications
    /// </summary>
    [Serializable]
    public class MinioNotification
    {
        public NotificationEvent[] Records;
        public String Err;
    }

    public class NotificationEvent
    {
        public String eventVersion;
        public String eventSource;
        public String awsRegion;
        public String eventTime;
        public String eventName;
        public Identity userIdentity;
        public Dictionary<String, String> requestParameters;
        public Dictionary<String, String> responseElements;
        public EventMeta s3;
        public SourceInfo source;
    }

    [DataContract]
    public class EventMeta
    {
        [DataMember]
        public String schemaVersion;

        [DataMember]
        public String configurationId;

        [DataMember]
        public BucketMeta bucket;

        [DataMember(Name = "object")]
        public ObjectMeta objectMeta; // C# won't allow the keyword 'object' as a name
    }

    public class ObjectMeta
    {
        public String key;
        public int size;
        public String etag;
        public String versionId;
        public String sequencer;
        public String contentType;
        public Dictionary<String, String> userMetadata;
    }

    public class BucketMeta
    {
        public String name;
        public Identity ownerIdentity;
        public String arn;
    }

    public class Identity
    {
        public String principalId;
    }

    public class SourceInfo
    {
        public String host;
        public String port;
        public String userAgent;
    }
}
